/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { smartUnion } from "../../types/smartUnion.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export enum AllowSyncEnum {
  Zero = "0",
  One = "1",
}
export type AllowSyncEnumOpen = OpenEnum<typeof AllowSyncEnum>;

export type AllowSync = boolean | AllowSyncEnumOpen;

/** @internal */
export const AllowSyncEnum$inboundSchema: z.ZodType<
  AllowSyncEnumOpen,
  unknown
> = openEnums.inboundSchema(AllowSyncEnum);

/** @internal */
export const AllowSync$inboundSchema: z.ZodType<AllowSync, unknown> =
  smartUnion([types.boolean(), AllowSyncEnum$inboundSchema]);

export function allowSyncFromJSON(
  jsonString: string,
): SafeParseResult<AllowSync, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AllowSync$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AllowSync' from JSON`,
  );
}
