/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  collectExtraKeys as collectExtraKeys$,
  safeParse,
} from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import { Part, Part$inboundSchema } from "./part.js";

/**
 * Voice activity detection availability flag returned by PMS.
 *
 * @remarks
 * PMS returns this as string values (`"0"` or `"1"`) instead of a JSON boolean.
 */
export enum HasVoiceActivity {
  False = 0,
  True = 1,
}
/**
 * Voice activity detection availability flag returned by PMS.
 *
 * @remarks
 * PMS returns this as string values (`"0"` or `"1"`) instead of a JSON boolean.
 */
export type HasVoiceActivityOpen = OpenEnum<typeof HasVoiceActivity>;

/**
 * `Media` represents an one or more media files (parts) and is a child of a metadata item. There aren't necessarily any guaranteed attributes on media elements since the attributes will vary based on the type. The possible attributes are not documented here, but they typically have self-evident names. High-level media information that can be used for badging and flagging, such as `videoResolution` and codecs, is included on the media element.
 *
 * @remarks
 */
export type Media = {
  aspectRatio?: number | undefined;
  audioChannels?: number | undefined;
  audioCodec?: string | undefined;
  audioProfile?: string | undefined;
  bitrate?: number | undefined;
  container?: string | undefined;
  duration?: number | undefined;
  has64bitOffsets?: boolean | undefined;
  /**
   * Voice activity detection availability flag returned by PMS.
   *
   * @remarks
   * PMS returns this as string values (`"0"` or `"1"`) instead of a JSON boolean.
   */
  hasVoiceActivity: HasVoiceActivityOpen;
  height?: number | undefined;
  id: number;
  optimizedForStreaming?: boolean | undefined;
  part?: Array<Part> | undefined;
  videoCodec?: string | undefined;
  videoFrameRate?: string | undefined;
  videoProfile?: string | undefined;
  videoResolution?: string | undefined;
  width?: number | undefined;
  additionalProperties?: { [k: string]: any } | undefined;
};

/** @internal */
export const HasVoiceActivity$inboundSchema: z.ZodType<
  HasVoiceActivityOpen,
  unknown
> = openEnums.inboundSchemaInt(HasVoiceActivity);

/** @internal */
export const Media$inboundSchema: z.ZodType<Media, unknown> = collectExtraKeys$(
  z.object({
    aspectRatio: types.optional(types.number()),
    audioChannels: types.optional(types.number()),
    audioCodec: types.optional(types.string()),
    audioProfile: types.optional(types.string()),
    bitrate: types.optional(types.number()),
    container: types.optional(types.string()),
    duration: types.optional(types.number()),
    has64bitOffsets: types.optional(types.boolean()),
    hasVoiceActivity: HasVoiceActivity$inboundSchema.default(
      HasVoiceActivity.False,
    ),
    height: types.optional(types.number()),
    id: types.number(),
    optimizedForStreaming: types.optional(types.boolean()),
    Part: types.optional(z.array(Part$inboundSchema)),
    videoCodec: types.optional(types.string()),
    videoFrameRate: types.optional(types.string()),
    videoProfile: types.optional(types.string()),
    videoResolution: types.optional(types.string()),
    width: types.optional(types.number()),
  }).catchall(z.any()),
  "additionalProperties",
  true,
).transform((v) => {
  return remap$(v, {
    "Part": "part",
  });
});

export function mediaFromJSON(
  jsonString: string,
): SafeParseResult<Media, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Media$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Media' from JSON`,
  );
}
